### ISSUE TITLE
return json with linkedin-scraper command

### ISSUE THREAD

**Issue by iliasnaamane** [yatish27/linkedin-scraper#101]
I get an error when running ' linkedin-scraper http://www.linkedin.com/in/jeffweiner output.json '

`/home/youpi/.rvm/gems/ruby-2.2.0/gems/linkedin-scraper-2.1.1/bin/linkedin-scraper:12:in `<top (required)>': uninitialized constant JSON (NameError)
	from /home/youpi/.rvm/gems/ruby-2.2.0/bin/linkedin-scraper:23:in `load'
	from /home/youpi/.rvm/gems/ruby-2.2.0/bin/linkedin-scraper:23:in `<main>'
	from /home/youpi/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/youpi/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
`

But it works well when working with code. Please kindly help me

**Comment by ajrasch** [comment]
@iliasnaamane Did you ever get this working from terminal? I'm having the same problem....

**Comment by iliasnaamane** [comment]
I have created a ruby file & run "ruby filename.rb linkedinUrl " then you will get linkedin profile in Json format. 
`
require 'linkedin-scraper'

profile = Linkedin::Profile.new("#{ARGV.first}")
puts profile.to_json`
