### ISSUE TITLE
Uninitialized Constant LinkedIn

### ISSUE THREAD

**Issue by rdempsey** [yatish27/linkedin-scraper#17]
When running the following in irb:

require 'linkedin-scraper'
profile = LinkedIn::Profile.get_profile("http://www.linkedin.com/in/robertwdempsey")

I get the following error:

NameError: uninitialized constant LinkedIn
    from (irb):2
    from /Users/roger/.rvm/rubies/ruby-1.9.3-p327/bin/irb:18:in `<main>'

I'm running ruby version 1.9.3p327 and have all the other required gems installed.

Any ideas?

Thanks!
- Robert

**Comment by dvc009** [comment]
I'm getting the same error even with: 
profile = Linkedin::Profile.get_profile("http://www.linkedin.com/in/jeffweiner08")

I'm using ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]

**Comment by NetanelBasal** [comment]
Any soultion to this problem?

**Comment by yatish27** [comment]
require 'linkedin_scraper'
profile = Linkedin::Profile.get_profile("http://www.linkedin.com/in/robertwdempsey")

**Comment by deuxio** [comment]
the "-" has been changed to "_" 

cf. @yatish27 answer
