### ISSUE TITLE
Returns nil in production but fine in development

### ISSUE THREAD

**Issue by mmahalwy** [yatish27/linkedin-scraper#21]
Using Ruby 2.1.1 and Rails 4.0.3

Development, works great. Production, I get this

999 =>  for  -- http://www.linkedin.com/in/mmahalwy

**Comment by santosh-btc** [comment]
agent = Mechanize.new

agent.get 'http://mediaserver-cont-ch1-2-v4v6.pandora.com/images/public/rovi/albumart/3/2/7/3/075679453723_500W_500H.jpg - work in local and give Mechanize::Page object.


agent.get 'http://mediaserver-cont-ch1-2-v4v6.pandora.com/images/public/rovi/albumart/3/2/7/3/075679453723_500W_500H.jpg - not working in production.gives Mechanize::Image object.


Please Help me.


'
