### ISSUE TITLE
Problem when linkedIn URL has accents

### ISSUE THREAD

**Issue by jcontesse** [yatish27/linkedin-scraper#26]
Is there another way I can write the URL?
I tried URLEncoding, etc.

linkedin-scraper http://cl.linkedin.com/pub/alejandra-peña-lazcano/61/9ab/68/en

/usr/local/bin/linkedin-scraper:13:in `<main>': invalid byte sequence in UTF-8 (ArgumentError)

**Comment by yatish27** [comment]
works fine on linux and mac test on latest ruby and latest gem
