### ISSUE TITLE
Company names are empty

### ISSUE THREAD

**Issue by dbounds** [yatish27/linkedin-scraper#37]
The past_companies collection is populated but the company names are empty for all but the first position. 

Profile used: https://www.linkedin.com/in/darrenbounds

**Comment by louwersj** [comment]
I have noticed the same issue... the majority of the companies are empty... also start_date and end_date are null (all tested in the JSON view)

**Comment by yatish27** [comment]
I will work on it tonight

On Thursday, January 1, 2015, Johan Louwers <notifications@github.com>
wrote:

> I have noticed the same issue... the majority of the companies are
> empty... also start_date and end_date are null (all tested in the JSON view)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/yatish27/linkedin-scraper/issues/37#issuecomment-68490124>
> .
>


-- 
Yatish Mehta

**Comment by louwersj** [comment]
Hi Yatish, sounds great... would be cool if this can be resolved as it will make the tool much more useful. I am looking into how I can use it to map social network connection by making use of neo4j... your code would really help as a feeder into neo4j :-)

Very much appreciated if you can fix this as I am not a ruby developer :-)

**Comment by yatish27** [comment]
@louwersj  which profile link are you testing it on

**Comment by yatish27** [comment]
@dbounds The code in master gives this output http://pastebin.com/WWhCjZpp

**Comment by louwersj** [comment]
As an example I am using: https://www.linkedin.com/in/innovativemarketingmanager 
When I look at the JSON output I notice that the company sections are empty.... 


Johan.

**Comment by yatish27** [comment]
I tried it worked for me. Try to install 0.1.5 version and then test

**Comment by cyberfab007** [comment]
has anyone got a version working with proxies yet ?

**Comment by cyberfab007** [comment]
if not I would be glad it get that done :)

**Comment by yatish27** [comment]
@cyberfab007 You can raise a PR

**Comment by wyngit** [comment]
Hello yatish, thanks so much for your efforts in this. I now have the reverse problem for some profiles: the current company field is populated, but the past companies fields are empty.

The profile in question is: http://www.linkedin.com/in/chicjai

Thanks again.
