### ISSUE TITLE
need to type in login info somewhere

### ISSUE THREAD

**Issue by huansun** [yatish27/linkedin-scraper#38]
The error message I got is here:

C:/Ruby193/lib/ruby/gems/1.9.1/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:70:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:70:in `block in connect'
	from C:/Ruby193/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
	from C:/Ruby193/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:70:in `connect'
	from C:/Ruby193/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
	from C:/Ruby193/lib/ruby/1.9.1/net/http.rb:751:in `start'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:259:in `fetch'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:976:in `response_redirect'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:300:in `fetch'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mechanize-2.7.3/lib/mechanize.rb:440:in `get'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/linkedin-scraper-0.1.3/lib/linkedin-scraper/profile.rb:20:in `initialize'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/linkedin-scraper-0.1.3/bin/linkedin-scraper:4:in `new'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/linkedin-scraper-0.1.3/bin/linkedin-scraper:4:in `<top (required)>'
	from C:/Ruby193/bin/linkedin-scraper:23:in `load'
	from C:/Ruby193/bin/linkedin-scraper:23:in `<main>'

Are there any configurations I have not done?

**Comment by scottjustin5000** [comment]
@huansun see: http://stackoverflow.com/questions/5720484/how-to-solve-certificate-verify-failed-on-windows (devdude's answer)
