### ISSUE TITLE
Get number of endorsements of each skill?

### ISSUE THREAD

**Issue by 123ndy** [yatish27/linkedin-scraper#42]
First of all: Great gem!

Second, I would love to get the number of endorsement of each skill. Would that be possible to implement?

**Comment by yatish27** [comment]
Will try to work on it next weekend

**Comment by 123ndy** [comment]
Great! I did some research on it today, and it seems that the "number of endorsement" is loaded into the page with some JS after the page is loaded in a browser. So I don't know if it is possible to do only with a Nokogiri...

**Comment by yatish27** [comment]
If it loaded with JS then it will be difficult to load
