### ISSUE TITLE
API not working any more

### ISSUE THREAD

**Issue by mlieber** [yatish27/linkedin-scraper#44]
hi,

I had the code installed on my own laptop a month ago, and everything worked fine.
Now, i just created a new instance on EC2, and installed/pulled the code, but getting:

ubuntu@ip-172-31-42-56:~$ linkedin-scraper http://www.linkedin.com/in/jeffweiner08
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:933:in `response_read': 999 =>  for  -- http://www.linkedin.com/in/jeffweiner08 (Mechanize::ResponseCodeError)
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:262:in `block in fetch'

This is the first call i am ever making, so it cannot be already blocked from Linkedin !! Do you know what could be happening ?
Thanks!
Matt

**Comment by tenji240** [comment]
Hi, 

I'm getting the same error. It works fine on my local machine, but running the command on an EC2 instance raises the same `999` error. 

Thanks,
Tenji

**Comment by yatish27** [comment]
Try booting up on Digitalocean

**Comment by drwl** [comment]
EC2 ip ranges have been blocked by LinkedIn which is why you get the 999.

**Comment by tadast** [comment]
Looks like Digital Ocean ip ranges have been blocked too :-1:

**Comment by yatish27** [comment]
You will need to by proxies as Linkedin is now smart to not allow bots/scraper to fetch data. Check the latest version 1.0.3. It allows to use proxies.

**Comment by hmphu** [comment]
@yatish27 Do you know any good and fresh proxy service? I want to buy many proxies to run the tool.

Thanks a lot

**Comment by yatish27** [comment]
@hmphu https://instantproxies.com/

**Comment by aaark** [comment]
Hi
Yatish27 
I am using linkedin scrapper gem and getting this error after requesting more than two or three times, would you please tell me the solution.

Mechanize::ResponseCodeError in LinkedinController#search
999 => for -- "xyz profile "

**Comment by tadast** [comment]
@aaark  LinkedIn does not want you to scrape their website, so after simultaneous requests they block your IP address. A solution would be to use a proxy server (i.e. channel all your scraping traffic through another server with IP that is not blacklisted yet), but it's only a matter of time until they detect and block the new IP address again, so there is no reliable solution unless you have access to many machines in different IP ranges. Popular provider IP ranges have been banned already, so you can't use AWS or Digital Ocean.
