### ISSUE TITLE
education description not working

### ISSUE THREAD

**Issue by kevinchugh** [yatish27/linkedin-scraper#47]
This always appears as empty string.

**Comment by kevinchugh** [comment]
Looks like this is because there are two h5's, one for the description, one for the college logo, the presence of college logo is tripping up this selector and causing an empty description.

**Comment by kevinchugh** [comment]
I keep getting a permission error to commit the fix, so here's the fix:

    change line 94 in lib/linkedin-scraper/profile.rb to
    desc   = item.search('h5').last

This will skip over the first h5 if present

**Comment by yatish27** [comment]
You can send a PR
