### ISSUE TITLE
Getting it to Work for a Company Page

### ISSUE THREAD

**Issue by Aaron-Hill** [yatish27/linkedin-scraper#48]
This has been working really great for me so far for individual public profiles, thank you. I'm really interested, though, in scraping a company page. Here's an example of one i'm interested in: 

https://www.linkedin.com/company/nestle-s-a-?trk=affco

These pages have a lot of unique data and we have a lot of potential accounts that we'd like to know the industry for, and/or number of employees. I understand that searching by individual yields company data. But we have a lot of company names for which we don't yet have contacts.

I'm interested in creating a version that could scrape company pages. I would be happy to create a pull and build it myself, and I will attempt to do so. Unfortunately I'm fairly new to programming and I'm very new to Ruby. So if you would be willing to give me a head start by telling me what files I should be modifying, or just help me build it, or (if you really feel like it) build it yourself, I would really appreciate it. Thanks so much!

**Comment by yatish27** [comment]
I will work on getting company profile information in the next version
