### ISSUE TITLE
Scraper not working

### ISSUE THREAD

**Issue by quovide** [yatish27/linkedin-scraper#62]
The scraper fails on profile picture:

/usr/local/share/gems/gems/linkedin-scraper-0.1.7/lib/linkedin_scraper/profile.rb:75:in `picture': undefined method `value' for nil:NilClass (NoMethodError)
        from /usr/local/share/gems/gems/linkedin-scraper-0.1.7/lib/linkedin_scraper/profile.rb:177:in `block in to_json'
        from /usr/local/share/gems/gems/linkedin-scraper-0.1.7/lib/linkedin_scraper/profile.rb:177:in `each'
        from /usr/local/share/gems/gems/linkedin-scraper-0.1.7/lib/linkedin_scraper/profile.rb:177:in `reduce'
        from /usr/local/share/gems/gems/linkedin-scraper-0.1.7/lib/linkedin_scraper/profile.rb:177:in `to_json'
        from /usr/local/share/gems/gems/linkedin-scraper-0.1.7/bin/linkedin-scraper:5:in `<top (required)>'
        from /usr/local/bin/linkedin-scraper:23:in `load'
        from /usr/local/bin/linkedin-scraper:23:in `<main>'

Maybe it is better to catch the exception and return a partial result

**Comment by yatish27** [comment]
Check latest version
