### ISSUE TITLE
v1  current_companies sometimes returns nil? false with nothing.

### ISSUE THREAD

**Issue by barthevandoorn** [yatish27/linkedin-scraper#64]

**Comment by yatish27** [comment]
Example link ?

**Comment by barthevandoorn** [comment]
http://www.linkedin.com/pub/james-dyer/8/663/4b3

On Wed, Dec 9, 2015 at 11:08 AM, Yatish Mehta <notifications@github.com>
wrote:

> Example link ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yatish27/linkedin-scraper/issues/64#issuecomment-163307733>
> .
>



-- 
______________
Barthe van Doorn  |  Barthe.vanDoorn@gmail.com  |  703.662.3781

**Comment by yatish27** [comment]
Check v1.0.1
