### ISSUE TITLE
Proxy on command line tool

### ISSUE THREAD

**Issue by 24601** [yatish27/linkedin-scraper#68]
Some comments in other issues indicate that a second command line arg can be used to allow usage of a proxy with the command line tool. That doesn't seem to be the case - looking at linkedin-scraper's source, it doesn't seem to call the gem with {:proxy_ip=>'127.0.0.1',:proxy_port=>'3128'} as the second arg.

Is this a feature that is planned? I'm not a ruby dev but this seems like it's easy enough to add, any interest in a PR?

**Comment by yatish27** [comment]
Check version 1.0.3
