### ISSUE TITLE
Scraper is conflating start and end date at companies

### ISSUE THREAD

**Issue by PepperTeasdale** [yatish27/linkedin-scraper#69]
Hi, I love the gem, but I am having some issues parsing the dates in Linkedin::Profile#past_companies

It looks like the hashes returned in #current_companies give start_date and end_date keys, while #past_companies only have start_date. Example output:
![screen shot 2016-02-14 at 12 13 51 pm](https://cloud.githubusercontent.com/assets/9939596/13035104/80fa862e-d315-11e5-86e7-b591d8152438.png)
Actual LinkedIn:
![screen shot 2016-02-14 at 12 21 50 pm](https://cloud.githubusercontent.com/assets/9939596/13035109/9cc6a108-d315-11e5-8010-a2b516a3346f.png)

Thanks

**Comment by yatish27** [comment]
Can you send the link of the Linkedin Profile ?

**Comment by PepperTeasdale** [comment]
Certainly, https://www.linkedin.com/in/timothypbuckley
Though, I noticed this with a number of profiles, not just this one. Have not tried dipping into the Mechanize/ Nokogiri level yet.
Thank you

**Comment by yatish27** [comment]
Fixed. Check latest commit and updated version 1.0.4. Thank you for pointing out the bug.

**Comment by PepperTeasdale** [comment]
Thank you!
