### ISSUE TITLE
A newbie has an Issue - Error: connection refused: www.linkedin.com:443

### ISSUE THREAD

**Issue by Didos1896** [yatish27/linkedin-scraper#75]
Hello everyone,
thanks for sharing this great gem!

I´m in the following situation: 
Soon, I´ll start to write my master thesis. To create the necessary data base I want use the information of a few thousand public linkedin profiles. 
I have never programed at all and currently try to find a way to create the data base. 
In this context I found this gem. While using this gem, I came to the issue, that I get the described issue. 
As soon as I use the following, I get the error below:  
profile = Linkedin::Profile.get_profile("https://www.linkedin.com/in/xxx", {:proxy_ip=>'127.0.0.1',:proxy_port=>'3128', :username=>"xxx", :password=>'xxx'}) 

output: connection refused: www.linkedin.com:443
=> nil

Can you help me on that? What does it mean? How can I solve the issue?

I wrote before, I am a totally newbie and glad about any help I can get. 
Do you have any general recommondation for my situation? Is this gem suitable for my issue?

Thanks alot

**Comment by jpegjames** [comment]
I'm getting a separate issue preventing me from getting it to work so I can't test this, but have you tried just sending it has an http request instead of https? The examples in the readme are http.

**Comment by yatish27** [comment]
https should work
Sometimes Linkedin blocks if you hit the server continuously
