### ISSUE TITLE
Scraper cannot scrape names somtimes

### ISSUE THREAD

**Issue by johnwu93** [yatish27/linkedin-scraper#80]
Sometimes when I scrape my own profile with url="https://www.linkedin.com/in/johnwu93", I am able to get my name by doing Linkedin::Profile.get_profile(url).name

However, sometimes, this will not work and Linkedin::Profile.get_profile(url) will actually return nil. I looked at the issues and it seems that the console will output a connection error and then the function will return nil. However, for my case, the console does not putout anything. Is there a way to fix this?

**Comment by haerde** [comment]
LinkedIn sometimes blocks connections. You should use proxy or tor.

**Comment by yatish27** [comment]
Use proxy instantproxies
