### ISSUE TITLE
Class name clash with 'browser' gem

### ISSUE THREAD

**Issue by cernyjakub** [yatish27/linkedin-scraper#90]
The new dependency on `random_user_agent` gem has added a nasty classname clash with widely used `browser` gem. Both gems define a `Browser` class without any namespacing.

I am afraid I am not the only one who was hit by this - it seems to me the `browser` gem is widely used.

**Comment by yatish27** [comment]
Yes, Seems like I need to included the 'random_user_agent' code in the gem with proper namespace, will fix it by tomorrow

**Comment by cernyjakub** [comment]
Great, latest update fixes the problem. Thanks!
