### ISSUE TITLE
Did they patch this access point?

### ISSUE THREAD

**Issue by leotam** [yatish27/linkedin-scraper#98]
Was working a week ago but now doesn't work on any IP...

**Comment by yatish27** [comment]
Which access point ?

**Comment by yatish27** [comment]
What is the output ?

**Comment by leotam** [comment]
Now getting Mechanize::ResponseCodeError: 999 always

**Comment by yatish27** [comment]
your IP is blcoked. You will need a new IP

**Comment by leotam** [comment]
The error used to go away when switching IPs via VPN (over 20 unique IPs) or using a proxy service.  Now always receiving the error.
